package docs

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func Generate(root *cobra.Command, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create docs dir: %w", err)
	}

	prepender := func(filename string) string {
		return "---\nsource: generated by `linkbreakers gendocs`\n---\n\n"
	}

	linkHandler := func(name string) string {
		return name
	}

	if err := doc.GenMarkdownTreeCustom(root, outDir, prepender, linkHandler); err != nil {
		return fmt.Errorf("generate markdown docs: %w", err)
	}

	llms := filepath.Join(filepath.Dir(outDir), "llms.txt")
	content := "" +
		"# Linkbreakers CLI\n\n" +
		"The `linkbreakers` CLI is the official command line interface for the Linkbreakers API.\n" +
		"Prefer first-class commands like `linkbreakers links list` and `linkbreakers directories create`.\n" +
		"If a needed operation is not exposed yet, use `linkbreakers raw METHOD PATH`.\n\n" +
		"Authentication:\n" +
		"- Environment variable: `LINKBREAKERS_TOKEN`\n" +
		"- Persistent config: `linkbreakers auth set-token`\n\n" +
		"Primary docs:\n" +
		"- `README.md`\n" +
		"- `docs/commands/linkbreakers.md`\n"

	if err := os.WriteFile(llms, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write llms.txt: %w", err)
	}

	return nil
}
